# Required
version: 2

formats:
  - epub
  - pdf

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
   install:
   - requirements: requirements.txt

sphinx:
   configuration: source/conf.py
